/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAenderungenIndexRouteImport } from './routes/_authenticated/aenderungen/index'
import { Route as AuthenticatedAenderungenIdRouteImport } from './routes/_authenticated/aenderungen/$id'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as AuthenticatedArchitekturIndexRouteImport } from './routes/_authenticated/architektur/index'
import { Route as AuthenticatedBrainIndexRouteImport } from './routes/_authenticated/brain/index'
import { Route as AuthenticatedDatenIndexRouteImport } from './routes/_authenticated/daten/index'
import { Route as AuthenticatedDokumenteIndexRouteImport } from './routes/_authenticated/dokumente/index'
import { Route as AuthenticatedDokumenteIdRouteImport } from './routes/_authenticated/dokumente/$id'
import { Route as AuthenticatedMcpIndexRouteImport } from './routes/_authenticated/mcp/index'
import { Route as AuthenticatedQualitaetIndexRouteImport } from './routes/_authenticated/qualitaet/index'
import { Route as AuthenticatedVerlaufIndexRouteImport } from './routes/_authenticated/verlauf/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAenderungenIndexRoute =
  AuthenticatedAenderungenIndexRouteImport.update({
    id: '/aenderungen/',
    path: '/aenderungen/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAenderungenIdRoute =
  AuthenticatedAenderungenIdRouteImport.update({
    id: '/aenderungen/$id',
    path: '/aenderungen/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchitekturIndexRoute =
  AuthenticatedArchitekturIndexRouteImport.update({
    id: '/architektur/',
    path: '/architektur/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrainIndexRoute = AuthenticatedBrainIndexRouteImport.update({
  id: '/brain/',
  path: '/brain/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatenIndexRoute = AuthenticatedDatenIndexRouteImport.update({
  id: '/daten/',
  path: '/daten/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDokumenteIndexRoute =
  AuthenticatedDokumenteIndexRouteImport.update({
    id: '/dokumente/',
    path: '/dokumente/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDokumenteIdRoute =
  AuthenticatedDokumenteIdRouteImport.update({
    id: '/dokumente/$id',
    path: '/dokumente/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMcpIndexRoute = AuthenticatedMcpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQualitaetIndexRoute =
  AuthenticatedQualitaetIndexRouteImport.update({
    id: '/qualitaet/',
    path: '/qualitaet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerlaufIndexRoute =
  AuthenticatedVerlaufIndexRouteImport.update({
    id: '/verlauf/',
    path: '/verlauf/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/aenderungen/$id': typeof AuthenticatedAenderungenIdRoute
  '/dokumente/$id': typeof AuthenticatedDokumenteIdRoute
  '/aenderungen/': typeof AuthenticatedAenderungenIndexRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/architektur/': typeof AuthenticatedArchitekturIndexRoute
  '/brain/': typeof AuthenticatedBrainIndexRoute
  '/daten/': typeof AuthenticatedDatenIndexRoute
  '/dokumente/': typeof AuthenticatedDokumenteIndexRoute
  '/mcp/': typeof AuthenticatedMcpIndexRoute
  '/qualitaet/': typeof AuthenticatedQualitaetIndexRoute
  '/verlauf/': typeof AuthenticatedVerlaufIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/aenderungen/$id': typeof AuthenticatedAenderungenIdRoute
  '/dokumente/$id': typeof AuthenticatedDokumenteIdRoute
  '/aenderungen': typeof AuthenticatedAenderungenIndexRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/architektur': typeof AuthenticatedArchitekturIndexRoute
  '/brain': typeof AuthenticatedBrainIndexRoute
  '/daten': typeof AuthenticatedDatenIndexRoute
  '/dokumente': typeof AuthenticatedDokumenteIndexRoute
  '/mcp': typeof AuthenticatedMcpIndexRoute
  '/qualitaet': typeof AuthenticatedQualitaetIndexRoute
  '/verlauf': typeof AuthenticatedVerlaufIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/aenderungen/$id': typeof AuthenticatedAenderungenIdRoute
  '/_authenticated/dokumente/$id': typeof AuthenticatedDokumenteIdRoute
  '/_authenticated/aenderungen/': typeof AuthenticatedAenderungenIndexRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/architektur/': typeof AuthenticatedArchitekturIndexRoute
  '/_authenticated/brain/': typeof AuthenticatedBrainIndexRoute
  '/_authenticated/daten/': typeof AuthenticatedDatenIndexRoute
  '/_authenticated/dokumente/': typeof AuthenticatedDokumenteIndexRoute
  '/_authenticated/mcp/': typeof AuthenticatedMcpIndexRoute
  '/_authenticated/qualitaet/': typeof AuthenticatedQualitaetIndexRoute
  '/_authenticated/verlauf/': typeof AuthenticatedVerlaufIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/aenderungen/$id'
    | '/dokumente/$id'
    | '/aenderungen/'
    | '/analytics/'
    | '/architektur/'
    | '/brain/'
    | '/daten/'
    | '/dokumente/'
    | '/mcp/'
    | '/qualitaet/'
    | '/verlauf/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/aenderungen/$id'
    | '/dokumente/$id'
    | '/aenderungen'
    | '/analytics'
    | '/architektur'
    | '/brain'
    | '/daten'
    | '/dokumente'
    | '/mcp'
    | '/qualitaet'
    | '/verlauf'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/aenderungen/$id'
    | '/_authenticated/dokumente/$id'
    | '/_authenticated/aenderungen/'
    | '/_authenticated/analytics/'
    | '/_authenticated/architektur/'
    | '/_authenticated/brain/'
    | '/_authenticated/daten/'
    | '/_authenticated/dokumente/'
    | '/_authenticated/mcp/'
    | '/_authenticated/qualitaet/'
    | '/_authenticated/verlauf/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aenderungen/': {
      id: '/_authenticated/aenderungen/'
      path: '/aenderungen'
      fullPath: '/aenderungen/'
      preLoaderRoute: typeof AuthenticatedAenderungenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aenderungen/$id': {
      id: '/_authenticated/aenderungen/$id'
      path: '/aenderungen/$id'
      fullPath: '/aenderungen/$id'
      preLoaderRoute: typeof AuthenticatedAenderungenIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/architektur/': {
      id: '/_authenticated/architektur/'
      path: '/architektur'
      fullPath: '/architektur/'
      preLoaderRoute: typeof AuthenticatedArchitekturIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brain/': {
      id: '/_authenticated/brain/'
      path: '/brain'
      fullPath: '/brain/'
      preLoaderRoute: typeof AuthenticatedBrainIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daten/': {
      id: '/_authenticated/daten/'
      path: '/daten'
      fullPath: '/daten/'
      preLoaderRoute: typeof AuthenticatedDatenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dokumente/': {
      id: '/_authenticated/dokumente/'
      path: '/dokumente'
      fullPath: '/dokumente/'
      preLoaderRoute: typeof AuthenticatedDokumenteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dokumente/$id': {
      id: '/_authenticated/dokumente/$id'
      path: '/dokumente/$id'
      fullPath: '/dokumente/$id'
      preLoaderRoute: typeof AuthenticatedDokumenteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mcp/': {
      id: '/_authenticated/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof AuthenticatedMcpIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qualitaet/': {
      id: '/_authenticated/qualitaet/'
      path: '/qualitaet'
      fullPath: '/qualitaet/'
      preLoaderRoute: typeof AuthenticatedQualitaetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verlauf/': {
      id: '/_authenticated/verlauf/'
      path: '/verlauf'
      fullPath: '/verlauf/'
      preLoaderRoute: typeof AuthenticatedVerlaufIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAenderungenIdRoute: typeof AuthenticatedAenderungenIdRoute
  AuthenticatedDokumenteIdRoute: typeof AuthenticatedDokumenteIdRoute
  AuthenticatedAenderungenIndexRoute: typeof AuthenticatedAenderungenIndexRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedArchitekturIndexRoute: typeof AuthenticatedArchitekturIndexRoute
  AuthenticatedBrainIndexRoute: typeof AuthenticatedBrainIndexRoute
  AuthenticatedDatenIndexRoute: typeof AuthenticatedDatenIndexRoute
  AuthenticatedDokumenteIndexRoute: typeof AuthenticatedDokumenteIndexRoute
  AuthenticatedMcpIndexRoute: typeof AuthenticatedMcpIndexRoute
  AuthenticatedQualitaetIndexRoute: typeof AuthenticatedQualitaetIndexRoute
  AuthenticatedVerlaufIndexRoute: typeof AuthenticatedVerlaufIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAenderungenIdRoute: AuthenticatedAenderungenIdRoute,
  AuthenticatedDokumenteIdRoute: AuthenticatedDokumenteIdRoute,
  AuthenticatedAenderungenIndexRoute: AuthenticatedAenderungenIndexRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedArchitekturIndexRoute: AuthenticatedArchitekturIndexRoute,
  AuthenticatedBrainIndexRoute: AuthenticatedBrainIndexRoute,
  AuthenticatedDatenIndexRoute: AuthenticatedDatenIndexRoute,
  AuthenticatedDokumenteIndexRoute: AuthenticatedDokumenteIndexRoute,
  AuthenticatedMcpIndexRoute: AuthenticatedMcpIndexRoute,
  AuthenticatedQualitaetIndexRoute: AuthenticatedQualitaetIndexRoute,
  AuthenticatedVerlaufIndexRoute: AuthenticatedVerlaufIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
